### ISSUE TITLE
node types were not found

### ISSUE THREAD

**Issue by ALFAMAN69** [Seedsa/Fooocus_Nodes#1]
When loading the graph, the following node types were not found:
Fooocus Loader[ 🔗](https://github.com/search?q=Fooocus%20Loader&type=code)
Nodes that have failed to load will show as red on the graph.

**Comment by Seedsa** [comment]
> When loading the graph, the following node types were not found: Fooocus Loader[ 🔗](https://github.com/search?q=Fooocus%20Loader&type=code) Nodes that have failed to load will show as red on the graph.

fixed. try reinstall the extension
