### ISSUE TITLE
How to use Fooocus detailerFix ?

### ISSUE THREAD

**Issue by MattRM2** [Seedsa/Fooocus_Nodes#20]
Hi,

Someone have an exemple on how to use Fooocus detailer workflow in comfyUI, not found exemple nowhere.
Thx

Matt

**Comment by mamorett** [comment]
I tried several options but does not seems to work. I got AttributeError: 'SDXL' object has no attribute 'latent_channels' regardless of the workflow I am using.

**Comment by MattRM2** [comment]
> I tried several options but does not seems to work. I got AttributeError: 'SDXL' object has no attribute 'latent_channels' regardless of the workflow I am using.

Hi, oki, thx for your answer.

Matt

**Comment by Seedsa** [comment]
should be fixed now
