### ISSUE TITLE
Error occurred when executing Fooocus KSampler: stack expects a non-empty TensorList

### ISSUE THREAD

**Issue by Sxrjs2010** [Seedsa/Fooocus_Nodes#21]
It runs successfully at first time, but error occurred at second time and more.
Here is the error code:
Error occurred when executing Fooocus KSampler:

stack expects a non-empty TensorList

File "/home/studio-lab-user/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/home/studio-lab-user/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/home/studio-lab-user/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/home/studio-lab-user/ComfyUI/custom_nodes/Fooocus_Nodes/py/fooocusNodes.py", line 764, in ksampler
base_image = torch.stack([tensor.squeeze() for tensor in all_imgs])

![image](https://github.com/Seedsa/Fooocus_Nodes/assets/137243324/4c9c397b-ff56-4535-85f3-36b47680df1a)

How to resolve it?
Thank you.

**Comment by Seedsa** [comment]
workflow pls

**Comment by Sxrjs2010** [comment]
[workflow-fooocus-text-sl9YxQ1umL1N9aRHtldI-datou-openart.ai_20240628.json](https://github.com/user-attachments/files/16065475/workflow-fooocus-text-sl9YxQ1umL1N9aRHtldI-datou-openart.ai_20240628.json)
@Seedsa 
Here it is.
Thanks!

**Comment by Seedsa** [comment]
<img width="1171" alt="screenshot" src="https://github.com/user-attachments/assets/0abdeef0-ce5c-4d42-b196-47422543b038">  it works fine now
