### ISSUE TITLE
fooocus style is not displayed

### ISSUE THREAD

**Issue by RainEmy** [Seedsa/Fooocus_Nodes#3]
Dear creator, thank you very much for integrating fooocus into comfyUI. My bro and I want to test the performance of the plugin, but we all encounter the same problem, that is, the style selector does not display the style, and an error will be reported when running, indicating that I need to select the style. We noticed that easy-use also has the same style selector. All the people who installed this node will encounter the same problem, so here to tell you, I hope there is a way to solve this problem, thanks for your hard work, thank you very much!
![{03ADEF7A-7F51-82A8-ECBB-A260661EAF7C}](https://github.com/Seedsa/Fooocus_Nodes/assets/112817003/4fc9561d-345b-4198-be66-fda906116d51)

**Comment by Seedsa** [comment]
Fixed.
