### ISSUE TITLE
Refiner cannot start normally

### ISSUE THREAD

**Issue by Lme53999** [Seedsa/Fooocus_Nodes#4]
Error occurred when executing Fooocus PreKSampler:

No such file or directory: "/sdXL_v10RefinerVAEFix.safetensors"

After selecting the refiner, I always get this error. I am sure that I have put the refiner in the checkpoints folder, and Fooocus Loader can read it, but I still get the error. What should I do?

**Comment by Seedsa** [comment]
fixed
