### ISSUE TITLE
Change of comfy.types to comfy.comfy_types

### ISSUE THREAD

**Issue by formulake** [Seedsa/Fooocus_Nodes#44]
ComfyUI's latest update broke the nodes because of a filename change that impacts line 31 of model_patcher.py. I've made the change manually as of now, to line 31 from:

`from comfy.types import UnetWrapperFunction`

to

`from comfy.comfy_types import UnetWrapperFunction`

**Comment by Piscabo** [comment]
I have the same issue:
_0.2 seconds (IMPORT FAILED): H:\ComfyUI\custom_nodes\Fooocus_Nodes_

  File "H:\ComfyUI\custom_nodes\Fooocus_Nodes\py\modules\core.py", line 8, in <module>
    import ldm_patched.modules.model_patcher
  File "H:\ComfyUI\custom_nodes\Fooocus_Nodes\py\ldm_patched\modules\model_patcher.py", line 31, in <module>
    from comfy.types import UnetWrapperFunction
ModuleNotFoundError: No module named 'comfy.types'

**Comment by formulake** [comment]
Till the nodes is updated, you can open the file located at H:\ComfyUI\custom_nodes\Fooocus_Nodes\py\ldm_patched\modules\model_patcher.py in a text editor like notepad++ and change line 31. It currently reads:
from comfy.types import UnetWrapperFunction

change it to:
from comfy.comfy_types import UnetWrapperFunction

It'll run fine after that.

**Comment by mrhan1993** [comment]
I think try catch is better, Otherwise, the older version will receive another import error, 😞
