### ISSUE TITLE
Index out of bounds when combining ImagePrompt + CPDS

### ISSUE THREAD

**Issue by aleph65** [Seedsa/Fooocus_Nodes#6]
Getting error when merging CPDS and ImagePrompt. Maybe I'm doing something wrong with the nodes? I've attached them here

Error occurred when executing Fooocus KSampler:

list index out of range

File "/workspace/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/workspace/ComfyUI/execution.py", line 81, in get_output_data

return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/workspace/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/workspace/ComfyUI/custom_nodes/Fooocus_Nodes/py/fooocusNodes.py", line 763, in ksampler
results = previewimage.save_images(
File "/workspace/ComfyUI/nodes.py", line 1404, in save_images
full_output_folder, filename, counter, subfolder, filename_prefix = folder_paths.get_save_image_path(filename_prefix, self.output_dir, images[0].shape[1], images[0].shape[0])

[imagePrompt_CPDS (1).json](https://github.com/Seedsa/Fooocus_Nodes/files/15058903/imagePrompt_CPDS.1.json)

**Comment by alexreitler** [comment]
I get this same Issue, please look into it

**Comment by MohammadAboulEla** [comment]
I tested this work flow and it works fine 
![Screenshot](https://github.com/Seedsa/Fooocus_Nodes/assets/89942942/945bbd95-de54-4416-8c3e-edc715f5cf72)
